package eu.nomad_lab.parsers

import eu.{ nomad_lab => lab }
import eu.nomad_lab.DefaultPythonInterpreter
import org.{ json4s => jn }
import scala.collection.breakOut

object OctopusParser extends SimpleExternalParserGenerator(
  name = "OctopusParser",
  parserInfo = jn.JObject(
    ("name" -> jn.JString("OctopusParser")) ::
      ("parserId" -> jn.JString("OctopusParser" + lab.OctopusVersionInfo.version)) ::
      ("versionInfo" -> jn.JObject(
        ("nomadCoreVersion" -> jn.JObject(lab.NomadCoreVersionInfo.toMap.map {
          case (k, v) => k -> jn.JString(v.toString)
        }(breakOut): List[(String, jn.JString)])) ::
          (lab.OctopusVersionInfo.toMap.map {
            case (key, value) =>
              (key -> jn.JString(value.toString))
          }(breakOut): List[(String, jn.JString)])
      )) :: Nil
  ),
  mainFileTypes = Seq("text/.*"),
  //TODO: Update the replacement string (mainFileRe)
  mainFileRe = """\*{32} Grid \*{32}
Simulation Box:
""".r,
  cmd = Seq(DefaultPythonInterpreter.pythonExe(), "${envDir}/parsers/octopus/parser/parser-octopus/parser_octopus.py",
    "${mainFilePath}"),
  resList = Seq(
    "parser-octopus/parser_octopus.py",
    "parser-octopus/aseoct.py",
    "parser-octopus/octopus_logfile_parser.py",
    "parser-octopus/generate-octopus-json.py",
    "parser-octopus/util.py",
    "parser-octopus/octopus_info_parser.py",
    "parser-octopus/setup_paths.py",
    "nomad_meta_info/public.nomadmetainfo.json",
    "nomad_meta_info/common.nomadmetainfo.json",
    "nomad_meta_info/meta_types.nomadmetainfo.json",
    "nomad_meta_info/octopus.autogenerated.nomadmetainfo.json",
    "nomad_meta_info/octopus.nomadmetainfo.json"
  ) ++ DefaultPythonInterpreter.commonFiles(),
  dirMap = Map(
    "parser-octopus" -> "parsers/octopus/parser/parser-octopus",
    "nomad_meta_info" -> "nomad-meta-info/meta_info/nomad_meta_info"
  ) ++ DefaultPythonInterpreter.commonDirMapping()
)
